### ISSUE TITLE
anyOf,oneOf,allOf是什么意思？

### ISSUE THREAD

**Issue by wjkang** [nick121212/fx-schema-form#3]

**Comment by nick121212** [comment]
anyOf: 满足任意一个
oneOf: 满足其中的一个，不能同时满足多个
allOf: 全部满足

**Comment by wjkang** [comment]
嗯，看了一遍Json Schema，有没有结合antd的例子？

**Comment by nick121212** [comment]
fx-schema-form-extension 这个项目里面的demo使用了antd。
